#!/usr/bin/env ruby

#--
# Copyright (c) 2007 - 2013 Jeremy Hinegardner
# All rights reserved. Licensed under the BSD license.  See LICENSE for details
#++

require 'heel'

Heel::Server.new(ARGV).run

